Repository SanaTameem/book-an-appointment-back-end, pull requests merged in 2023-11, with the labels that each got.

#14 Project setup
  .dockerignore
  .gitattributes
  .github/workflows/linters.yml
  .gitignore
  .rubocop.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
  Rakefile
  app/channels/application_cable/channel.rb
  app/channels/application_cable/connection.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/.keep
  app/jobs/application_job.rb
  app/mailers/application_mailer.rb
  app/models/application_record.rb
  app/models/concerns/.keep
  app/views/layouts/mailer.html.erb
  app/views/layouts/mailer.text.erb
  bin/bundle
  bin/bundle.cmd
  bin/docker-entrypoint
  bin/rails
  bin/rake
  bin/setup
  config.ru
  config/application.rb
  config/boot.rb
  config/cable.yml
  config/credentials.yml.enc
  config/database.yml
  config/environment.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/cors.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/inflections.rb
  config/locales/en.yml
  config/puma.rb
  config/routes.rb
  config/storage.yml
  db/seeds.rb
  lib/tasks/.keep
  log/.keep
  public/robots.txt
  storage/.keep
  tmp/.keep
  tmp/pids/.keep
  tmp/storage/.keep
  vendor/.keep
Labels: Massam's Task

#16 Feature/show item
  app/controllers/api/v1/cars_controller.rb
  config/routes.rb
  spec/requests/api/v1/cars_spec.rb
Labels: Sana's Task

#17 Feature/Destroy item
  app/controllers/api/v1/cars_controller.rb
  config/routes.rb
Labels: Sana's Task

#18 Authentication
  app/controllers/api/v1/users_controller.rb
  app/models/user.rb
  config/routes.rb
  db/migrate/20231114043852_create_users.rb
  db/schema.rb
  spec/models/user_spec.rb
Labels: Massam's Task

#19 Feature/main page
  app/controllers/api/v1/cars_controller.rb
  app/models/car.rb
  app/models/user.rb
  db/seeds.rb
Labels: Sana's Task

#20 Add devise and jwt for Authentication
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/users_controller.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/rack_session_fix.rb
  app/controllers/users/registrations_controller.rb
  app/controllers/users/sessions_controller.rb
  app/models/user.rb
  app/serializers/user_serializer.rb
  config/environments/development.rb
  config/initializers/cors.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20231115074941_add_devise_to_users.rb
  db/migrate/20231115080131_add_jti_to_users.rb
  db/schema.rb
Labels: Massam's Task

#23 Car adding serialized.
  app/serializers/car_seralizer.rb
Labels: Melkamu's Task

#24 implement the destroy action controller for reservation.
  app/controllers/api/v1/reservations_controller.rb
  app/models/car.rb
  config/application.rb
Labels: Melkamu's Task

#25 Api Doc
  .rspec
  Gemfile
  Gemfile.lock
  MIT.md
  README.md
  app/controllers/api/v1/users_controller.rb
  app/controllers/reservation_controller.rb
  app/models/car.rb
  app/models/user.rb
  app/serializers/user_serializer.rb
  config/initializers/rswag_api.rb
  config/initializers/rswag_ui.rb
  config/routes.rb
  db/seeds.rb
  spec/models/car_spec.rb
  spec/models/reservation_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/requests/api/v1/cars_spec.rb
  spec/requests/cars_spec.rb
  spec/requests/reservation_spec.rb
  spec/spec_helper.rb
  swagger/v1/swagger.yaml
Labels: Massam's Task
